 substitutions:
  name: "vantreeseba-smart-speaker"
  friendly_name: "Smart Speaker"
  
  # Config
  i2c_freq: 400khz

  # PINS
  uart_tx_pin: GPIO17
  uart_rx_pin: GPIO18

  i2c_sda_pin: GPIO21
  i2c_scl_pin: GPIO20

  rmt_rgb_pin: GPIO19

  i2s_out_data_pin: GPIO07
  i2s_out_lrclk_pin: GPIO15
  i2s_out_bclk_pin: GPIO16

  i2s_in_lrclk_pin: GPIO9
  i2s_in_bclk_pin: GPIO10
  i2s_in_data_pin: GPIO12

external_components:
  - source: github://pr#5674
    components: [ld2450]
  - source: 
      type: git
      url: https://github.com/esphome/home-assistant-voice-pe
      ref: dev
    components:
      - audio_dac
      - media_player
      - micro_wake_word
      - microphone
      - nabu
      - nabu_microphone
      - voice_assistant
    refresh: 0s

## BOARD CONFIG
esphome:
  name: ${name}
  project:
    name: "vantreeseba.smart_speaker"
    version: "0.1.0"
  friendly_name: ${friendly_name}
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    - speaker.play:
        data: [0x00]

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
      # CONFIG_ESP32_S3_BOX_BOARD: "y"
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      # Settings based on https://github.com/espressif/esp-adf/issues/297#issuecomment-783811702
      CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "16"
      CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "512"
      CONFIG_ESP32_WIFI_STATIC_TX_BUFFER: "y"
      CONFIG_ESP32_WIFI_TX_BUFFER_TYPE: "0"
      CONFIG_ESP32_WIFI_STATIC_TX_BUFFER_NUM: "8"
      CONFIG_ESP32_WIFI_CACHE_TX_BUFFER_NUM: "32"
      CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED: "y"
      CONFIG_ESP32_WIFI_TX_BA_WIN: "16"
      CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED: "y"
      CONFIG_ESP32_WIFI_RX_BA_WIN: "32"
      CONFIG_LWIP_MAX_ACTIVE_TCP: "16"
      CONFIG_LWIP_MAX_LISTENING_TCP: "16"
      CONFIG_TCP_MAXRTX: "12"
      CONFIG_TCP_SYNMAXRTX: "6"
      CONFIG_TCP_MSS: "1436"
      CONFIG_TCP_MSL: "60000"
      CONFIG_TCP_SND_BUF_DEFAULT: "65535"
      CONFIG_TCP_WND_DEFAULT: "65535"  # Adjusted from linked settings to avoid compilation error
      CONFIG_TCP_RECVMBOX_SIZE: "512"
      CONFIG_TCP_QUEUE_OOSEQ: "y"
      CONFIG_TCP_OVERSIZE_MSS: "y"
      CONFIG_LWIP_WND_SCALE: "y"
      CONFIG_TCP_RCV_SCALE: "3"
      CONFIG_LWIP_TCPIP_RECVMBOX_SIZE: "512"
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5

logger:
  hardware_uart: uart0
  # level: VERBOSE
  # logs:
  #   sensor: WARN  # avoids logging debug sensor updates

api:
  # on_client_connected:
  #   - speaker.play:
  #       data: [0x00]

ota:
  - platform: esphome

wifi:
  reboot_timeout: 0s
  output_power: 10dB
  enable_btm: True
  enable_rrm: True
  ssid: !secret wifi_ssid
  password: !secret wifi_password

psram:
  mode: octal
  speed: 80MHz

## BUSES/ETC
i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: $i2s_in_lrclk_pin
    i2s_bclk_pin: $i2s_in_bclk_pin
  - id: i2s_out
    i2s_lrclk_pin: $i2s_out_lrclk_pin
    i2s_bclk_pin: $i2s_out_bclk_pin

uart:
  id: uart_ld2450
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

## Light
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: $rmt_rgb_pin
    num_leds: 10
    rmt_channel: 0
    chipset: ws2812
    name: "LED Ring"
    use_psram: false

## Audio Components
microphone:
  - platform: i2s_audio
    id: inmp_441
    i2s_mode: primary
    i2s_audio_id: i2s_in
    i2s_din_pin: $i2s_in_data_pin
    adc_type: external
    sample_rate: 16000
    bits_per_sample: 32bit
    pdm: false
    # channel: left
    channel: right

speaker:
  - platform: i2s_audio
    i2s_mode: primary
    i2s_audio_id: i2s_out
    id: i2s_speaker
    dac_type: external
    i2s_dout_pin: $i2s_out_data_pin
    sample_rate: 48000
    channel: mono
    buffer_duration: 500ms
    use_apll: true

media_player:
  - platform: nabu
    id: nabu_media_player
    name: Media Player
    internal: false
    speaker: i2s_speaker
    sample_rate: 48000
    volume_increment: 0.05
    on_announcement:
      - nabu.set_ducking:
          decibel_reduction: 20
          duration: 0.0s
    on_state:
      if:
        condition:
          - not:
              lambda: return id(nabu_media_player)->state == media_player::MediaPlayerState::MEDIA_PLAYER_STATE_ANNOUNCING;
        then:
          - nabu.set_ducking:
              decibel_reduction: 0
              duration: 1.0s

# VOICE CONFIGS
# micro_wake_word:
#   id: mww
#   microphone: inmp_441
#   models:
#     - model: https://github.com/kahrendt/microWakeWord/releases/download/okay_nabu_20241226.3/okay_nabu.json
#       id: okay_nabu
#     - model: hey_jarvis
#       id: hey_jarvis
#     - model: https://github.com/kahrendt/microWakeWord/releases/download/stop/stop.json
#       id: stop
#       internal: true
#   on_wake_word_detected:
#     - logger.log: "WAKE WORD DETECTED!!!!"
      # - micro_wake_word.stop:
      # - voice_assistant.start:
      #     wake_word: !lambda return wake_word;

voice_assistant:
  id: va
  microphone: inmp_441
  media_player: nabu_media_player
  # micro_wake_word: mww
  # Defaults
  use_wake_word: true
  # Events
  on_start:
    - nabu.set_ducking:
        decibel_reduction: 20   # Number of dB quieter; higher implies more quiet, 0 implies full volume
        duration: 0.0s          # The duration of the transition (default is 0)
  # on_tts_streaming: 
  #   - nabu.set_ducking:
  #       decibel_reduction: 0
  #       duration: 1.0s
  on_error: 
    - nabu.set_ducking:
        decibel_reduction: 0
        duration: 1.0s
  on_client_connected:
    - delay: 5s
    - voice_assistant.start_continuous:
  on_client_disconnected:
    - voice_assistant.stop:
      

#### OLED DISPLAY
font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto_16
    size: 16
  - file: "gfonts://Roboto"
    id: roboto_32
    size: 32

### Display / I2C
## BUSSES
i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  scan: true
  frequency: ${i2c_freq}

time:
  id: ntp_time
  platform: sntp
  timezone: America/Chicago

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C #Default
    # external_vcc: True
    # update_interval: 5s
    lambda: |-
      auto cur_time = id(ntp_time).now();
      it.strftime(0, 0, id(roboto_32), "%X", cur_time);
      // auto temperature = ((id(aht10_temp).state / 5) * 9) + 32;
      // auto humidity = id(aht10_humidity).state;
      // it.printf(0, 48, id(roboto_16), "%4.1f°F %12.1f%%", temperature, humidity);

# LD2450 Config
ld2450:
  id: ld2450_radar
  uart_id: uart_ld2450
  throttle: 1000ms

number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    presence_timeout:
      name: "Timeout"

# switch:
#   - platform: ld2450
#     ld2450_id: ld2450_radar
#     bluetooth:
#       name: "Bluetooth"
#       restore_mode: ALWAYS_OFF
#       disabled_by_default: true
#     multi_target:
#       name: "Multi Target Tracking"
#       disabled_by_default: true

button:
  - platform: ld2450
    ld2450_id: ld2450_radar
    factory_reset:
      name: "LD2450 Factory Reset"
      entity_category: "config"
    restart:
      name: "LD2450 Restart"
      entity_category: "config"

# select:
#   - platform: ld2450
#     ld2450_id: ld2450_radar
#     baud_rate:
#       name: "Baud rate"

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

sensor:
  # - platform: aht10
  #   temperature:
  #     id: aht10_temp
  #     name: "${friendly_name} Temperature"
  #     filters:
  #     - offset: ${temperature_offset}
  #   humidity:
  #     id: aht10_humidity
  #     name: "${friendly_name} Humidity"
  #   update_interval: 30s
  # - platform: bh1750
  #   name: "${friendly_name} Illuminance"
  #   address: 0x23
  #   update_interval: 5s
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: Presence Target Count
    still_target_count:
      name: Still Target Count
    moving_target_count:
      name: Moving Target Count
    target_1:
      x:
        name: Target-1 X
      y:
        name: Target-1 Y
      speed:
        name: Target-1 Speed
        internal: true 
      angle:
        name: Target-1 Angle
        internal: true 
      distance:
        name: Target-1 Distance
        internal: true 
      resolution:
        name: Target-1 Resolution
        internal: true 
    target_2:
      x:
        name: Target-2 X
      y:
        name: Target-2 Y
      speed:
        name: Target-2 Speed
        internal: true 
      angle:
        name: Target-2 Angle
        internal: true 
      distance:
        name: Target-2 Distance
        internal: true 
      resolution:
        name: Target-2 Resolution
        internal: true 
    target_3:
      x:
        name: Target-3 X
      y:
        name: Target-3 Y
      speed:
        name: Target-3 Speed
        internal: true 
      angle:
        name: Target-3 Angle
        internal: true 
      distance:
        name: Target-3 Distance
        internal: true 
      resolution:
        name: Target-3 Resolution
        internal: true
