esphome:
  name: minimal
  friendly_name: 1_minimal
  platformio_options:
    board_build.flash_mode: dio
  # on_boot:
  #   - lambda: |-
  #       id(my_ota).set_auth_password("");

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
    platform_version: 6.4.0
    version: 5.1.1

external_components:
  # use rtttl and dfplayer from ESPHome's dev branch in GitHub
  - source: github://pr#5535
    components: [ ota ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.0.164

ota:
  id: my_ota
  password: my_ota_password
  unprotected_writes: True # This is mandatory if you want to flash the partition table or bootloader!
    
