substitutions:
  name: "vantreeseba-multisensor"
  friendly_name: "Multisensor"
  temperature_offset: "-3"

esphome:
  name: "${name}"
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: vantreeseba.multisensor
    version: "2.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
api:
ota:
wifi:
  # use_address: vantreeseba-multisensor-a1c820.lan
  use_address: vantreeseba-multisensor-2d35c0.lan
  # use_address: vantreeseba-multisensor-7eb164.lan
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: 25
  scl: 32
  scan: true

sensor:
  - platform: aht10
    temperature:
      name: "${friendly_name} Temperature"
      filters:
      - offset: ${temperature_offset}
    humidity:
      name: "${friendly_name} Humidity"
    update_interval: 30s
  - platform: bh1750
    name: "${friendly_name} Illuminance"
    address: 0x23
    update_interval: 5s

binary_sensor:
  - platform: gpio
    pin: GPIO27
    name: "${friendly_name} PIR Sensor"
    device_class: motion

#BLE STUFF
# bluetooth_proxy:
#   active: True
  
# esp32_ble_tracker: 
#   scan_parameters:
#     # interval: 100ms
#     # window: 30ms
#     duration: 5s
