substitutions:
  device_name: waveshare-p4-touch-lcd-4
  device_friendly_name: Waveshare P4 Touch LCD 4
  mic_din_pin: GPIO11
  speaker_dout_pin: GPIO9
  amp_switch_pin: GPIO53

packages:
  base:
    url: https://github.com/vantreeseba/home_automation
    ref: main
    file: shared_packages/waveshare_p4_base.yaml
  codecs:
    url: https://github.com/vantreeseba/home_automation
    ref: main
    file: shared_packages/es8311_es7210_audio.yaml
  mixer_resampler:
    url: https://github.com/vantreeseba/home_automation
    ref: main
    file: shared_packages/mixer_resampler_speakers.yaml

touchscreen:
  - platform: gt911
    id: touchscreen_

## PANEL BACKLIGHT CONFIG
output:
  - platform: ledc
    id: backlight_
    pin: GPIO26
    frequency: 100Hz
    inverted: true
    # min_power: 0.1 # To prevent the backlight from being too dim
    max_power: 0.8 # To prevent overheating due to excessive lighting

light:
  - platform: monochromatic
    name: "backlight"
    output: backlight_
    id: backlight_light
    restore_mode: ALWAYS_ON

display:
  - platform: mipi_dsi
    id: my_display
    model: WAVESHARE-ESP32-P4-WIFI6-TOUCH-LCD-4C
    pixel_mode: 16bit
    color_depth: 16
    draw_rounding: 4
