substitutions:
  name: "vantreeseba-multisensor"
  friendly_name: "Multisensor"
  temperature_offset: "-3"

esphome:
  name: "${name}"
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: vantreeseba.multisensor
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  # level: VERY_VERBOSE

# Enable Home Assistant API
api:
ota:
wifi:
  use_address: vantreeseba-multisensor-26382c.lan
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#BLE STUFF
# bluetooth_proxy:
#   active: True
# esp32_ble_tracker:
#   scan_parameters:
#     duration: 2s

# Bus / Configs
i2c:
  sda: 25
  scl: 32
  scan: true

# Sensors
sensor:
  - platform: aht10
    temperature:
      name: "${friendly_name} Temperature"
      filters:
      - offset: ${temperature_offset}
    humidity:
      name: "${friendly_name} Humidity"
    update_interval: 30s
  - platform: bh1750
    name: "${friendly_name} Illuminance"
    address: 0x23
    update_interval: 5s

binary_sensor:
  - platform: gpio
    pin: GPIO35
    name: "${friendly_name} PIR Sensor"
    device_class: motion
