substitutions:
  device_name: waveshare-p4-wifi6-touch-lcd-7b
  device_friendly_name: Waveshare P4 WiFi6 Touch LCD 7B
  mic_din_pin: GPIO11
  speaker_dout_pin: GPIO9
  amp_switch_pin: GPIO53

packages:
  base:
    url: https://github.com/vantreeseba/home_automation
    ref: main
    file: home_automation/shared_packages/waveshare_p4_base.yaml
  codecs:
    url: https://github.com/vantreeseba/home_automation
    ref: main
    file: home_automation/shared_packages/es8311_es7210_audio.yaml
  mixer_resampler:
    url: https://github.com/vantreeseba/home_automation
    ref: main
    file: home_automation/shared_packages/mixer_resampler_speakers.yaml

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

psram:
  mode: hex
  speed: 200MHz

esp_ldo:
  - voltage: 2.5V
    channel: 3

# -------------------------------------------
# Touchscreen gt911 i2c
# -------------------------------------------
i2c:
  - id: i2c_bus
    sda: GPIO07
    scl: GPIO08
    frequency: 400kHz

touchscreen:
  - platform: gt911
    id: my_touchscreen
    i2c_id: i2c_bus
    reset_pin: GPIO23
    update_interval: 50ms
    transform:
      swap_xy: false
      mirror_x: true
      mirror_y: true

# -------------------------------------------
# Backlight
# -------------------------------------------
output:
  - platform: ledc
    id: gpio_backlight_pwm
    pin: GPIO32
    inverted: true
    frequency: 1000Hz

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# -------------------------------------------
# Display
# -------------------------------------------
display:
  - platform: mipi_dsi
    id: my_display
    model: WAVESHARE-ESP32-P4-WIFI6-TOUCH-LCD-7B
    rotation: 180
    dimensions:
      width: 1024
      height: 600

# -------------------------------------------
# audio
# -------------------------------------------
i2s_audio:
  - id: i2s_bus
    i2s_mclk_pin: GPIO13
    i2s_lrclk_pin: GPIO10
    i2s_bclk_pin: GPIO12
