esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}

logger:

ota:
  - platform: esphome

wifi:
  id: wifi_id
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

psram:
  mode: octal

api:

number:
  - platform: template
    id: sleep_duration
    name: Sleep Duration
    max_value: 3600
    min_value: 30
    step: 30
    device_class: duration
    unit_of_measurement: seconds
    entity_category: config
    optimistic: True
    initial_value: 360
    restore_value: True

button:
  - platform: restart
    name: "Restart"
    entity_category: "diagnostic"
