substitutions:
  device_name: photo-frame-1
  device_friendly_name: Photo Frame 1
  display_pixel_width: '800'
  display_pixel_height: '480'
  display_min_pixel_x: '0'
  display_min_pixel_y: '0'
  display_rotation: '270°'

packages:
  base: !include ../shared_packages/photopainter_base.yaml
  hw: !include ../shared_packages/photopainter_hw.yaml
  display: !include ../shared_packages/photopainter_display.yaml
  sendspin: !include ../shared_packages/photopainter_sendspin.yaml
