substitutions:
  display_pixel_width: '480'   # Right most visible pixel
  display_pixel_height: '800'   # bottom most visible pixel -- 
  display_min_pixel_x: '0'
  display_min_pixel_y: '0'
  display_rotation: '90°'

logger:
ota:
  - platform: esphome

wifi:
  id: wifi_id
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

esphome:
  name: photo-frame-1
  friendly_name: Photo Frame 1
  min_version: 2025.5.0
  on_boot:
    priority: 800
    then:
      - lambda: |- # Turn on the power of the display
          id(bus).write(0x34, (uint8_t[]){0x95, 0x1C}, 2);

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

psram:
  mode: octal

api:
  actions:
  - action: epaper_reload_image
    then:
      - lambda: |-
          id(sendspin_cover_art).update();

  - action: epaper_render
    then:
      - lambda: |-
          id(my_display).update();

external_components:
  - source: github://pr#12284
    components: [generic_image, sendspin]
    refresh: 0s

sendspin:
  id: sendspin_hub
  task_stack_in_psram: true

generic_image:
  - platform: sendspin
    id: sendspin_cover_art
    format: jpg
    type: RGB
    resize: ${display_pixel_width}x${display_pixel_height}
    image_source: ALBUM
    on_image_decoded:
      - lambda: |-
          ESP_LOGI("sendspin", "Cover art decoded");
          id(image_downloading_events).trigger("image_downloading_complete");
      - component.update: my_display
    on_image_error:
      - lambda: |-
          ESP_LOGE("sendspin", "Failed to decode cover art image");
          id(image_downloading_events).trigger("image_downloading_failed");

# event configuration
event:
  - platform: template
    name: Rendering
    id: rendering_events
    icon: "mdi:brush"
    event_types:
      - render_complete
  - platform: template
    name: Image Downloading
    id: image_downloading_events
    icon: "mdi:download"
    event_types:
      - image_downloading_complete
      - image_downloading_failed

switch:
  - platform: template
    name: "Download and render on startup"
    id: auto_load_render
    icon: "mdi:cloud-download-outline"
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true

interval:
  - interval: 1h  # Base interval for the check
    then:
      - lambda: |-
          if (id(auto_screen_refresh).state > 0) {
            id(auto_refresh_counter)++;

            if (id(auto_refresh_counter) >= id(auto_screen_refresh).state) {
              id(auto_refresh_counter) = 0;  // Reset counter
              ESP_LOGI("${TAG}", "Timer triggered re-rendering");
              id(my_display).update();
            }
          }

number:
  - platform: template
    name: "Auto Screen refresh"
    id: auto_screen_refresh
    unit_of_measurement: "h"
    icon: "mdi:refresh-auto"
    optimistic: true
    min_value: 0
    max_value: 96
    step: 1
    initial_value: 0
    on_value:
      then:
        - lambda: |-
            id(auto_refresh_counter) = 0;  // Reset counter
            if (x == 0) {
              ESP_LOGI("${TAG}", "Disable auto screen refresh");
            } else {
              ESP_LOGI("${TAG}", "Auto screen refresh updated: %.0fh", x);
            }

globals:
  - id: auto_refresh_counter
    type: int
    restore_value: no
    initial_value: '0'

button:
  - platform: template
    name: "Reload image"
    entity_category: diagnostic
    on_press:
      - lambda: |-
          id(sendspin_cover_art).update();

  - platform: template
    name: "Render"
    entity_category: diagnostic
    on_press:
      - lambda: |-
          id(my_display).update();

i2c:
  id: bus
  sda: GPIO47
  scl: GPIO48
  scan: true

sensor:
  - platform: shtcx
    temperature:
      id: temperature
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
      accuracy_decimals: 1
    humidity:
      id: humidity
      unit_of_measurement: "%"
      device_class: humidity
      state_class: measurement

spi:
  clk_pin: GPIO10
  mosi_pin: GPIO11

display:
  - platform: epaper_spi
    id: my_display
    model: 7.3in-spectra-e6
    cs_pin: GPIO9
    dc_pin: GPIO8
    busy_pin: 
      number: GPIO13
      inverted: true
      mode:
        input: true
        pullup: true
    reset_pin: 
      number: GPIO12
    update_interval: never
    rotation: 270°
    show_test_card: true
    lambda: |-
      static const char *TAG = "${TAG} - Rendering cycle";

      ESP_LOGW(TAG, "Rendering...");

      it.fill(COLOR_OFF);
      if(id(wifi_id).is_connected()) {
        // Fullscreen sendspin cover art image
        it.image(${display_min_pixel_x}, ${display_min_pixel_y}, id(sendspin_cover_art), COLOR_OFF, COLOR_ON);
      } else { 
        ESP_LOGW(TAG, "Wifi not connected. Using offline image");
        // Centered offline placeholder
        int mid_x = $display_min_pixel_x + $display_pixel_width / 2;
        int mid_y = $display_min_pixel_y + $display_pixel_height / 2;
        it.circle(mid_x, mid_y, 10);
      }

      ESP_LOGW(TAG, "Rendering done");
      id(rendering_events).trigger("render_complete");

font:
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20
